# Generated by Django 2.0.5 on 2018-06-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchDateApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_participant',
            name='participant_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session_participant',
            name='participant_location_index',
            field=models.IntegerField(default=0),
        ),
    ]
